### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nfriedly** [nfriedly/contributor-locations#1]
* [ ] A way to cancel an in-progress load
    * Fire it automatically if a new one is initiated
        * (Or just keep multiple on the screen?)
    * https://getbootstrap.com/docs/5.3/components/close-button/
* [ ] Look into reducing queries with graphql - https://docs.github.com/en/graphql/guides/forming-calls-with-graphql
* [ ] Make it slowly finish when rate-limited
* [ ] Logo & favicon
* [ ] Make the summary easier to read
* [ ] Add a way to report bad country matches?
* [ ] Offer to store token in localStorage
* [ ] Build a better location->country tool (AI/ML)
